// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotKayit.Models.DataContext;

#nullable disable

namespace NotKayit.Migrations
{
    [DbContext(typeof(NotKayitDbContext))]
    [Migration("20260217150457_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotKayit.Models.Entities.DersAlanKodTml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DersAlanKodTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.DersTml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("DersAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DersAlanKodId")
                        .HasColumnType("int");

                    b.Property<short>("KrediSayisi")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DersAlanKodId");

                    b.ToTable("DersTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.NotKodTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NotKodTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.NotTml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Deger")
                        .HasColumnType("float");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<long>("NotKodId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotKodTmlId")
                        .HasColumnType("int");

                    b.Property<long>("OgrenciId")
                        .HasColumnType("bigint");

                    b.Property<int>("OgrenciTmlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("NotKodId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("NotTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("OgrenciId")
                        .HasColumnType("bigint");

                    b.Property<int>("OgrenciTmlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciAdres");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<long>("OgrenciId")
                        .HasColumnType("bigint");

                    b.Property<int>("OgrenciTmlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciIletisim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OgrenciTmlId")
                        .HasColumnType("bigint");

                    b.Property<long>("Telefon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciTmlId");

                    b.ToTable("OgrenciIletisim");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OgrenciTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.DersTml", b =>
                {
                    b.HasOne("NotKayit.Models.Entities.DersAlanKodTml", "DersAlanKod")
                        .WithMany()
                        .HasForeignKey("DersAlanKodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersAlanKod");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.NotTml", b =>
                {
                    b.HasOne("NotKayit.Models.Entities.DersTml", "Ders")
                        .WithMany("Notlar")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotKayit.Models.Entities.NotKodTml", "NotKod")
                        .WithMany()
                        .HasForeignKey("NotKodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotKayit.Models.Entities.OgrenciTml", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("NotKod");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciAdres", b =>
                {
                    b.HasOne("NotKayit.Models.Entities.OgrenciTml", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciDers", b =>
                {
                    b.HasOne("NotKayit.Models.Entities.DersTml", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotKayit.Models.Entities.OgrenciTml", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.OgrenciIletisim", b =>
                {
                    b.HasOne("NotKayit.Models.Entities.OgrenciTml", "OgrenciTml")
                        .WithMany()
                        .HasForeignKey("OgrenciTmlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrenciTml");
                });

            modelBuilder.Entity("NotKayit.Models.Entities.DersTml", b =>
                {
                    b.Navigation("Notlar");

                    b.Navigation("OgrenciDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
